### ISSUE TITLE
Infinity arrow not trapped

### ISSUE THREAD

**Issue by SlimeDog** [Ruinscraft/CHIP#3]
CHIP did not trap this illegal enchantment on an arrow:
> /enchant infinity 1

(It was trapped by Essentials)

CHIP/config.yml
```
remove_item: false
remove_entity: false
ops_bypass_checks: false
world_whitelist:
  use: true
  worlds:
  - world
  - world_nether
  - world_the_end
notifications:
  chat: false
  console: true
allowed_modifications:
  enchantments:
    above_normal_enchants: false
    below_normal_enchants: false
    conflicting_enchants: false
  fireworks:
    non_craftable_fireworks: false
  item_meta:
    custom_lore: true
    unbreakable_items: false
    colored_custom_names: true
    colored_custom_lore: true
  entities:
    invulnerable: false
    glowing: false
    custom_name_visible: false
    armor_stands:
      small: false
      visible: false
      base_plate: false
      no_arms: false
  nbt:
    attribute_modifiers: false
    custom_potions: false
    death_loot_table: false
    size: false
    entity_tag: false
    explosion_radius: false
    tile_entity_data: false
    block_entity_tag: false
max_custom_name_length: 35
max_custom_lore_length_per_line: 64
ignore_head_names: true
ignore_head_lores: true
env_blocking:
  enable_env_blocking: false
  notify_console_when_cancelled: false
  water_flow: false
  lava_flow: false
  tnt_update: false
  sponge_update: false
```
